### ISSUE TITLE
Length of Encryption Key is '1' which is less than '50'

### ISSUE THREAD

**Issue by ChristopherHarveyDev** [Shahprogrammer/Django-CryptographicFields#3]
Followed Quick start guide entirely, generated my own ENCRYPTION_KEY.
All requirements met

Received ExceptionType: LengthError

Also, small type on import
from CrptographicFields import fields
should be
from CryptographicFields import fields

**Comment by Shahprogrammer** [comment]
You were getting that error because your encryption key should have minimum length of 50 chars

**Comment by Shahprogrammer** [comment]
@ChristopherHarveyDev check the documentation
https://django-cryptographicfields.readthedocs.io/en/latest/
